version: '3'
services:
  ory-hydra-go:
    container_name: ory-hydra-go
    build:
      context: .
      dockerfile: go.Dockerfile
    ports:
      - "3000:3000"
#    command: time bash sleep1.sh
    command: go run main.go
      - .:/code
    working_dir: /code
    depends_on:
      - go-psql

  go-psql:
    container_name: go-psql
    image: postgres:9.5.6-alpine
    volumes:
      - ~/mainsite:/var/lib/postgresql/data
    ports:
      - 0.0.0.0:5433:5432