version: '3'
services:
  ory-hydra-go:
    container_name: ory-hydra-go
    build:
      context: .
      dockerfile: go.Dockerfile
    ports:
      - "3000:3000"
#    command: time bash sleep1.sh
    command: go run main.go
      - .:/code
    working_dir: /code